### ISSUE TITLE
Feature / When video is pause/played resume playback from server time

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#1]
We could somehow on the frontend catch the played-after-manual-pausing the YouTube video and get a server playtime so we can resume at the correct place/time. 
For this we would need to have the YouTube player started with the JS API, now it's just in an iframe.

**Comment by IvayloAtanasov** [comment]
:+1:  Since we will need the JS API anyway, I can start doing some research about that and see where it leads me.

**Comment by IvayloAtanasov** [comment]
I think that one's done. Tried to push up my branch to open a pull request but I got 'Permission denied'. Maybe I need to be added to contributors list first? If so can you add me please :)

**Comment by Bratanov** [comment]
Hello Mr. Atanasov,
To contribute to the repo I believe you have to fork the repo, add it as an origin to the forked repo to pull the branch and then you should be able to open a pull request here on github. Here's the official guide: https://guides.github.com/activities/contributing-to-open-source/ and a SO page: http://stackoverflow.com/questions/4384776/how-do-i-contribute-to-others-code-in-github 
Thank you for your contribution and let me know how it goes. :rocket: I would be also cool to have a contributions guide here, but one step at a time.

**Comment by Bratanov** [comment]
Merged and ready for production! 🦃 Yey! :)
