### ISSUE TITLE
Feature / Allow Fullscreen

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#2]
Not sure if we could do this without allowing controls on the video, could be included in YouTube's APIs.

**Comment by Bratanov** [comment]
Also note: You can double click the video to go fullscreen, but that's a bit hackish and not so user friendly.

**Comment by IvayloAtanasov** [comment]
Doesn't seem so hackish anymore. I suggest closing that issue.

**Comment by Bratanov** [comment]
Closing as it's both not a much needed feature and achievable with the current setup (although not clearly indicated, can be counted as a hidden double-click-to-fullscreen feature)
