### ISSUE TITLE
Feature / Volume Controls

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#3]
Currently there's no way to change the player's volume. We can have a custom volume thingie.

For this we would need to have the YouTube player started with the JS API, now it's just in an iframe.

**Comment by cmihaylov** [comment]
When I need to mute/pause the sound, I can click on the video and the song is paused (effectively muted). BUT when the next song starts, the sound automatically is turned ON again.

**Comment by HristoEftimov** [comment]
The same issue as @cmihaylov. +1 for the idea :)

**Comment by IvayloAtanasov** [comment]
We don't need volume controls all that much. User is unlikely to want a volume different than the one set on OS level. I think it would just clutter the UI with no particular valie.

The mute button, on the other hand is much requested feature and will be available soon with https://github.com/Bratanov/community-driven-radio/pull/37

**Comment by Bratanov** [comment]
Muting will be available with #37 
Volume controls not needed, can reopen if this feature is requested. 🚀
