### ISSUE TITLE
Bug / Embeddable message is emitted to everyone

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#36]
Here: https://github.com/Bratanov/community-driven-radio/blob/2465e93/server/core/queue.js#L112

Whoops.

**Comment by IvayloAtanasov** [comment]
Fixed here: https://github.com/Bratanov/community-driven-radio/pull/33/commits/c18930b8acfad766334e89ef65e65c759b64c7cf

**Comment by Bratanov** [comment]
Fixed in #33
