### ISSUE TITLE
Feature / Server check to skip videos blocked by region

### ISSUE THREAD

**Issue by Bratanov** [Bratanov/community-driven-radio#4]
We shouldn't start playing servers blocked in BG (for example). This info is returned with the song info from YouTube's server APIs.

**Comment by IvayloAtanasov** [comment]
I think [this](https://github.com/Bratanov/community-driven-radio/pull/33/commits/c18930b8acfad766334e89ef65e65c759b64c7cf) should do the trick.
[documentation reference](https://developers.google.com/youtube/v3/docs/videos)
Kind of dislike the hardcoding of 'BG' but I guess we can live with it 😃

**Comment by Bratanov** [comment]
Implemented in #33
Kind of hardcoded for BG, but when environment variables are extracted per server it can be put there. (So the server specifies which countries are blocked)
